name: grow_in_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_database: ^11.3.0
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.5
  test: ^1.25.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/branding/
    - assets/images/item_image/
    - assets/images/logo/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  ios: true
  android: true
  web: true

  color: "#d4e4ed"

  background_image: "assets/images/background.png"
  image: "assets/images/logo.png"
  branding: "assets/images/branding.png"

  background_image_dark: "assets/images/background_dark.png"
  image_dark: "assets/images/logo_dark.png"
  branding_dark: "assets/images/branding_dark.png"
